Extra/better tests and comments

diff --git a/autoload/ssh/start_ssh_agent b/autoload/ssh/start_ssh_agent
--- a/autoload/ssh/start_ssh_agent
+++ b/autoload/ssh/start_ssh_agent
@@ -1,23 +1,44 @@
+# Ensure ssh agent details are shared across terminal sessions
+# Benefits:
+#  - enter passphrase only once
+#  - no duplicate agents
+
 # ssh-agent -l seems to be a MAC OS thing only
 if [[ $(pgrep -fl ssh-agent | grep -v 'ssh[-]agent -l' | wc -l) > 1 ]]
 then
    {
-      print -P '%F{red}Found multiple ssh agents%f:'
+      print -P '%F{red}Aborted ssh agent after detecting multiple instances%f:'
       pg ssh-agent
    } 1>&2
    return 1
 fi
 
-if ! ssh-add -l >/dev/null 2>&1
+ssh-add -l >/dev/null 2>&1
+# Error connecting to agent
+if [[ $? == 2 ]]
 then
+   # try connecting using persisted details: sock and PID
    if [[ -r ~/.ssh/env ]]
    then
       eval $(<~/.ssh/env) >/dev/null
    fi
-   if ! ssh-add -l >/dev/null 2>&1
+
+   # if connecting still fails, it either means there is no actual agent process
+   # or it runs with different details
+   ssh-add -l >/dev/null 2>&1
+   if [[ $? == 2 ]]
    then
-      (umask 066; ssh-agent -s -t36000 > ~/.ssh/env)
-      eval $(<~/.ssh/env) >/dev/null
-      ssh-add
+      if pgrep -fl ssh-agent | grep -qv 'ssh[-]agent -l'
+      then
+         {
+            print -P '%F{red}Aborted ssh agent after detecting an instance with mismatched details%f:'
+            pg ssh-agent
+         } 1>&2
+      else
+         # launch agent
+         (umask 066; ssh-agent -s -t36000 > ~/.ssh/env)
+         eval $(<~/.ssh/env) >/dev/null
+         ssh-add
+      fi
    fi
 fi
