Fix the local arr=() error...

diff --git a/.zsh/autoload/cv b/.zsh/autoload/cv
--- a/.zsh/autoload/cv
+++ b/.zsh/autoload/cv
@@ -1,43 +1,74 @@
 ## Convert to dec, bin, oct, hex
-(($#)) || { echo 'Usage: cv digit ...' >&2; return 1; }
 
-cvs[0]='Decimal to binary'
-cvs[1]='Decimal to octal'
-cvs[2]='Decimal to hexadecimal'
-cvs[3]='Binary to decimal'
-cvs[4]='Octal to decimal'
-cvs[5]='Hexadecimal to decimal'
+if (($# == 0))
+then
+   echo 'Usage: cv digit ...' 1>&2
+   return 1
+fi
 
-local cv PS3='.? '
+typeset -a cvs
 
-select cv in "${cvs[@]}"; do
-   case "$cv" in
-      "${cvs[0]}")
-         while read -r; do
-            printf '%d -> %d\n' "$1" "$REPLY"; shift
-         done < <(IFS=';'; command bc -q <<< "obase=2; $*") |\
-         command sed '1iDec -> Bin' | column -t
+cvs[1]='Decimal to binary'
+cvs[2]='Decimal to octal'
+cvs[3]='Decimal to hexadecimal'
+cvs[4]='Binary to decimal'
+cvs[5]='Octal to decimal'
+cvs[6]='Hexadecimal to decimal'
+
+local PS3='.? '
+
+select cv in $cvs
+do
+   case $cv in
+
+      ($cvs[1])
+         while read -r
+         do
+            printf '%d -> %d\n' $1 $REPLY
+            shift
+         done < <(IFS=';'; bc -q <<< "obase=2; $*") | sed '1iDec -> Bin' | column -t
          break;;
-      "${cvs[1]}")
-         while (($#)); do printf '%d -> %o\n' "$1" "$1"; shift; done |\
-         command sed '1iDec -> Oct' | column -t
+
+      ($cvs[2])
+         while (($#))
+         do
+            printf '%d -> %o\n' $1 $1
+            shift
+         done | sed '1iDec -> Oct' | column -t
          break;;
-      "${cvs[2]}")
-         while (($#)); do printf '%d -> %x\n' "$1" "$1"; shift; done |\
-         command sed '1iDec -> Hex' | column -t
+
+      ($cvs[3])
+         while (($#))
+         do
+            printf '%d -> %x\n' $1 $1
+            shift
+         done | sed '1iDec -> Hex' | column -t
          break;;
-      "${cvs[3]}")
-         while (($#)); do printf '%d -> %d\n' "$1" "$((2#$1))"; shift; done |\
-         command sed '1iBin -> Dec' | column -t
+
+      ($cvs[4])
+         while (($#))
+         do
+            printf '%d -> %d\n' $1 "$((2#$1))"
+            shift
+         done | sed '1iBin -> Dec' | column -t
          break;;
-      "${cvs[4]}")
-         while (($#)); do printf '%d -> %d\n' "$1" "$((8#$1))"; shift; done |\
-         command sed '1iOct -> Dec' | column -t
+
+      ($cvs[5])
+         while (($#))
+         do
+            printf '%d -> %d\n' $1 "$((8#$1))"
+            shift
+         done | sed '1iOct -> Dec' | column -t
          break;;
-      "${cvs[5]}")
-         while (($#)); do printf '%s -> %d\n' "$1" "$((16#$1))"; shift; done |\
-         command sed '1iHex -> Dec' | column -t
+
+      ($cvs[6])
+         while (($#))
+         do
+            printf '%s -> %d\n' $1 "$((16#$1))"
+            shift
+         done | sed '1iHex -> Dec' | column -t
          break;;
-                *) printf '\nInvalid choice!\n' >&2
+
+            (*) printf '\nInvalid choice!\n' >&2
    esac
 done
