rsall: remove -u for user. $1 could be user@host anyway... rseverywhere: pass options to rsall rsvim: add comment

diff --git a/autoload/net/rseverywhere b/autoload/net/rseverywhere
--- a/autoload/net/rseverywhere
+++ b/autoload/net/rseverywhere
@@ -3,6 +3,23 @@
 # Usage: rseverywhere [@dt...]
 #                     +-- http://clustershell.readthedocs.io/en/latest/tools/nodeset.html
 
+# store options on order to pass them to rsall below
+OPTIND=1
+
+local opt
+local -a opts
+while getopts :gdn opt
+do
+   case $opt in
+      [gdn]) opts+=($opt) ;;
+         \?) echo "Invalid option: -$OPTARG" 1>&2
+             return 1 ;;
+   esac
+done
+
+shift $((OPTIND-1))
+
+# check hosts
 if (($#))
 then
    print -P '%F{yellow}Syncing config on these hosts%f:'
@@ -14,11 +31,12 @@ fi
 
 echo
 read 'REPLY?proceed? '
-[[ $REPLY == (#i)(y|yes) ]] || return 1
+[[ $REPLY == (#i)(y|yes) ]] || return 2
 
+# sync
 # TODO: fix -d '' <--> -S'\0'
 while read -r
 do
    print -P "%F{yellow}$REPLY%f"
-   rsall $REPLY
+   rsall ${opts/#/-} $REPLY
 done < <(nodeset -e -S'\n' ${@:--a})
